StylesPath = .vale/styles
MinAlertLevel = suggestion

Packages = Google, proselint

Vocab = config

[*]
BasedOnStyles = Vale, Google, proselint

# Disable rules that don't fit technical documentation
Vale.Terms = NO
Google.Headings = NO
Google.Exclamation = NO
Google.Will = NO
Google.Parens = NO
Google.Passive = NO
Google.Ellipses = NO
proselint.Annotations = NO
proselint.Typography = NO
